name: deploy on push
on: [push]

jobs:
  deploy-app:
    runs-on: ubuntu-latest
    steps:
    - name: 54.209.202.5
    uses: actions/checkout@v2
    - name: index.html
    uses: appleboy/scp-action@master
    with:
      host: ${{secrets.HOST}}
      username: ${{secrets.SSH_USER_NAME}}
      port: ${{secrets.SSH_PORT}}
      key: ${{secrets.SSH_KEY}}
      source: "./html/*"
      target: "/var/www/html"
      strip_components: 1
